steps:
  - label: Build
    command: ./auto/build
    artifact_paths: "dist/*"

  - label: Docs Build
    command: ./auto/docs-build

  - wait

  - label: "Upload Release Pipeline"
    command: ./auto/upload-release-pipeline
    branches:
      - main

  - label: Deploy Docs
    command: ./auto/docs-deploy
    branches:
      - main
