#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")/.."

SERVICE="${SERVICE:-build}"

docker-compose build "$SERVICE"

SERVICE_PORTS_FLAG=${SERVICE_PORTS:+--service-ports}
docker-compose run --rm ${SERVICE_PORTS_FLAG} "$SERVICE" "${@-bash}"
