CREATE TABLE IF NOT EXISTS `#__gausers_invoices` (
`id` int unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
`ordering` int NOT NULL DEFAULT 0,
`state` tinyint NOT NULL DEFAULT 0,
`checked_out` int NULL,
`checked_out_time` datetime NULL,
`created_date` datetime NULL,
`created_by` int NOT NULL DEFAULT 0,
`modified_date` datetime NULL,
`modified_by` int  NOT NULL  DEFAULT 0,
`user_id` int NOT NULL DEFAULT 0,
`invoice_amt` decimal(11,2) NOT NULL DEFAULT 0.00,
`paid_date` date NULL,
`memtype` int  NOT NULL DEFAULT 0,
`mship_id` int  NOT NULL DEFAULT 0,
`end_date` date NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__gausers_profile_audit` (
`id` int unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
`ordering` int  NOT NULL DEFAULT 0,
`state` tinyint  NOT NULL DEFAULT 0,
`checked_out` int  NULL,
`checked_out_time` datetime NULL,
`created_by` int  NOT NULL  DEFAULT 0,
`created_date` datetime NULL,
`user_id` int  NOT NULL  DEFAULT 0,
`data_audit` text NULL ,
`pre_update` text NULL ,
`post_update` text NULL ,
`comment` text NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__gausers_club_execs` (
`id` int unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
`ordering` int  NOT NULL  DEFAULT 0,
`state` tinyint  NOT NULL  DEFAULT 0,
`checked_out` int  NULL,
`checked_out_time` datetime NULL,
`created_by` int  NOT NULL  DEFAULT 0,
`created_date` datetime NULL ,
`modified_by` int  NOT NULL  DEFAULT 0,
`modified_date` datetime NULL,
`club_id` int  NOT NULL  DEFAULT 0,
`club_name` varchar(255)  NULL ,
`club_address` varchar(255)  NULL ,
`club_suburb` varchar(255)  NULL ,
`club_pcode` varchar(25)  NULL ,
`club_phone` varchar(100)  NULL ,
`club_email` varchar(255)  NULL ,
`use_clubemail` tinyint  NOT NULL DEFAULT 0,
`club_website` varchar(1024)  NULL ,
`club_logo` varchar(1024)  NULL ,
`club_region` tinyint  NOT NULL DEFAULT 0,
`meeting_day` varchar(255)  NULL ,
`meeting_time` time  NOT NULL DEFAULT '00:00:00',
`meeting_info` text NULL ,
`meeting_address` varchar(255)  NULL ,
`integ_mbrs` tinyint  NOT NULL DEFAULT 0,
`pres_id` int  NOT NULL  DEFAULT 0,
`pres_idp` tinyint  NOT NULL  DEFAULT 0,
`pres_name` varchar(255)  NULL ,
`vpres_id` int  NOT NULL  DEFAULT 0,
`vpres_idp` tinyint  NOT NULL  DEFAULT 0,
`vpres_name` varchar(255)  NULL ,
`secr_id` int  NOT NULL  DEFAULT 0,
`secr_idp` tinyint  NOT NULL  DEFAULT 0,
`secr_name` varchar(255)  NULL ,
`tres_id` int  NOT NULL  DEFAULT 0,
`tres_idp` tinyint  NOT NULL  DEFAULT 0,
`tres_name` varchar(255)  NULL ,
`edit_id` int  NOT NULL  DEFAULT 0,
`edit_idp` tinyint  NOT NULL  DEFAULT 0,
`edit_name` varchar(255)  NULL ,
`delg_id` int  NOT NULL  DEFAULT 0,
`delg_idp` tinyint  NOT NULL  DEFAULT 0,
`delg_name` varchar(255)  NULL ,
`regr_id` int  NOT NULL  DEFAULT 0,
`regr_idp` tinyint  NOT NULL  DEFAULT 0,
`regr_name` varchar(255)  NULL ,
`istc_id` int  NOT NULL  DEFAULT 0,
`istc_idp` tinyint  NOT NULL  DEFAULT 0,
`istc_name` varchar(255)   NULL ,
`end_term` date NULL,
`comment` text NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__gausers_mshiptypes` (
`id` int unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
`ordering` int NOT NULL DEFAULT 0,
`state` tinyint NOT NULL DEFAULT 0,
`checked_out` int NULL,
`checked_out_time` datetime NULL,
`created_date` datetime NULL,
`created_by` int NOT NULL DEFAULT 0,
`modified_date` datetime NULL,
`modified_by` int  NOT NULL  DEFAULT 0,
`title` varchar(255)  NULL ,
`joining_fee` decimal(11,2) NOT NULL DEFAULT 0.00,
`subscrib_amt` decimal(11,2) NOT NULL DEFAULT 0.00,
`discount_amt` decimal(11,2) NOT NULL DEFAULT 0.00,
`term_type` varchar(255) NOT NULL DEFAULT 'YEAR',
`mship_term` int NOT NULL DEFAULT 1,
`comment` text NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

INSERT INTO `#__gausers_mshiptypes` (`id`, `ordering`, `state`, `checked_out`, `checked_out_time`, `created_date`, `created_by`, `modified_date`, `modified_by`, `title`, `joining_fee`, `subscrib_amt`, `discount_amt`, `term_type`, `mship_term`, `comment`) VALUES
(1, 1, 1, 0, NULL, '2022-11-03 00:00:00', 0, '2022-11-03 00:00:00', 0, 'Probationary', '0.00', '0.00', '0.00', 'YEAR', 1, ''),
(2, 2, 1, 0, NULL, '2022-11-03 00:00:00', 0, '2022-11-03 00:00:00', 0, 'Full', '0.00', '0.00', '0.00', 'YEAR', 1, ''),
(3, 3, 1, 0, NULL, '2022-11-03 00:00:00', 0, '2022-11-03 00:00:00', 0, 'Life', '0.00', '0.00', '0.00', 'YEAR', 0, '');

CREATE TABLE IF NOT EXISTS `#__gausers_actions` (
`id` int unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
`ordering` int NOT NULL DEFAULT 0,
`state` tinyint NOT NULL DEFAULT 0,
`checked_out` int NULL,
`checked_out_time` datetime DEFAULT NULL,
`created_by` int NOT NULL DEFAULT 0,
`created_date` datetime DEFAULT NULL,
`modified_by` int NOT NULL DEFAULT 0,
`modified_date` datetime DEFAULT NULL,
`user_id` int NOT NULL DEFAULT 0,
`cat_id` int  NOT NULL DEFAULT 0,
`act_name` varchar(1024) NULL,
`comment` text NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;
