ALTER TABLE `#__gatracklog_tracklogs` change `ordering` `ordering` INT(11)  NOT NULL DEFAULT 0;
ALTER TABLE `#__gatracklog_tracklogs` change `state` `state` TINYINT(1)  NOT NULL DEFAULT 0;
ALTER TABLE `#__gatracklog_tracklogs` change `created_by` `created_by` INT(11)  NOT NULL DEFAULT 0;
ALTER TABLE `#__gatracklog_tracklogs` change `created_date` `created_date` DATETIME NULL;
ALTER TABLE `#__gatracklog_tracklogs` change `checked_out` `checked_out` INT(11)  NOT NULL DEFAULT 0;
ALTER TABLE `#__gatracklog_tracklogs` change `checked_out_time` `checked_out_time` DATETIME NULL;
ALTER TABLE `#__gatracklog_tracklogs` change `modified_by` `modified_by` INT(11)  NOT NULL DEFAULT 0;
ALTER TABLE `#__gatracklog_tracklogs` change `update_date` `modified_date` DATETIME NULL;
ALTER TABLE `#__gatracklog_tracklogs` change `rating` `rating` INT(11)  NOT NULL DEFAULT 0;
ALTER TABLE `#__gatracklog_tracklogs` change `track_zone` `track_zone` INT(11)  NOT NULL DEFAULT 0;
ALTER TABLE `#__gatracklog_tracklogs` change `season_close` `season_close` INT(11)  NOT NULL DEFAULT 0;
ALTER TABLE `#__gatracklog_tracklogs` change `trklog` `trklog` TEXT NULL;
ALTER TABLE `#__gatracklog_tracklogs` change `comment` `comment` TEXT NULL;
ALTER TABLE `#__gatracklog_tracklogs` change `name` `name` VARCHAR(255) NULL;
ALTER TABLE `#__gatracklog_tracklogs` change `file_format` `file_format` VARCHAR(255) NULL;

ALTER TABLE `#__gatracklog_trackcomments` change `ordering` `ordering` INT(11)  NOT NULL DEFAULT 0;
ALTER TABLE `#__gatracklog_trackcomments` change `state` `state` TINYINT(1)  NOT NULL DEFAULT 0;
ALTER TABLE `#__gatracklog_trackcomments` change `created_by` `created_by` INT(11)  NOT NULL DEFAULT 0;
ALTER TABLE `#__gatracklog_trackcomments` change `created_date` `created_date` DATETIME NULL;
ALTER TABLE `#__gatracklog_trackcomments` change `checked_out` `checked_out` INT(11)  NOT NULL DEFAULT 0;
ALTER TABLE `#__gatracklog_trackcomments` change `checked_out_time` `checked_out_time` DATETIME NULL;
ALTER TABLE `#__gatracklog_trackcomments` change `modified_by` `modified_by` INT(11)  NOT NULL DEFAULT 0;
ALTER TABLE `#__gatracklog_trackcomments` change `update_date` `modified_date` DATETIME NULL;
ALTER TABLE `#__gatracklog_trackcomments` change `user_id` `user_id` INT(11)  NOT NULL DEFAULT 0;
ALTER TABLE `#__gatracklog_trackcomments` change `track_id` `track_id` INT(11)  NOT NULL DEFAULT 0;
ALTER TABLE `#__gatracklog_trackcomments` change `comment` `comment` TEXT NULL;

ALTER TABLE `#__gatracklog_tracklogs` ENGINE=InnoDB;
ALTER TABLE `#__gatracklog_tracklogs` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `#__gatracklog_trackcomments` ENGINE=InnoDB;
ALTER TABLE `#__gatracklog_trackcomments` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
